services:
  app:
    image: node:16.14.0-alpine3.14
    container_name: 'ignem-arcanium'
    user: 1000:1000
    working_dir: /app
    expose:
      - 8000
    volumes:
      - .:/app
    command: npm run dev
