services:
  app:
    image: node:16.14.0-alpine3.14
    container_name: 'ignem-arcanium'
    user: 1000:1000
    working_dir: /app
    expose:
      - 8000
    depends_on:
      - pg
    volumes:
      - .:/app
    command: npm run dev

  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pg-tests:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d